name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./去除控制.sln  # Specify the exact path to your solution file

  # Configuration type to build.
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Modify PlatformToolset to v143
      run: |
        sed -i 's/<PlatformToolset>v100<\/PlatformToolset>/<PlatformToolset>v143<\/PlatformToolset>/g' ./去除控制/去除控制.vcxproj

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Set PlatformToolset to v143 for Visual Studio 2022 compatibility
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:PlatformToolset=v143 ${{env.SOLUTION_FILE_PATH}}
